version: "3.9"

services:
  #Postgres database
  db: 
    image: postgres 
    restart: always 
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lensgallery # Database name
    ports: 
      - 5432:5432 

  # 
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
